name: social_embed_webview
description: Provide a widget to easily embed social media post in flutter using web embed feature by the platform.
version: 0.3.1
homepage: https://github.com/aker99/social_embed_webview

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.3
  webview_flutter: ^2.0.4
  localstorage: ^4.0.0+1
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
